# Generated by Django 3.0 on 2024-01-09 18:54

from django.db import migrations
from django.core.serializers import deserialize
import os

def restore_profile(apps, schema_editor):
    with open('profile_backup.json', 'r') as f:
        data = f.read()
    data = data.replace('oc_lettings_site.profile', 'profiles.profile')
    for obj in deserialize("json", data):
        obj.save()
    os.remove('profile_backup.json')

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0002_auto_20240109_1946'),
    ]

    operations = [
        migrations.RunPython(restore_profile),
    ]
