# Generated by Django 3.0 on 2024-01-09 18:49

from django.db import migrations
from django.core.serializers import deserialize
import os

def restore_letting(apps, schema_editor):
    with open('letting_backup.json', 'r') as f:
        data = f.read()
    data = data.replace('oc_lettings_site.letting', 'lettings.letting')
    for obj in deserialize("json", data):
        obj.save()
    os.remove('letting_backup.json')

def restore_address(apps, schema_editor):
    with open('address_backup.json', 'r') as f:
        data = f.read()
    data = data.replace('oc_lettings_site.address', 'lettings.address')
    for obj in deserialize("json", data):
        obj.save()
    os.remove('address_backup.json')


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
        ('oc_lettings_site', '0002_auto_20240109_1946'),
    ]

    operations = [
        migrations.RunPython(restore_address),
        migrations.RunPython(restore_letting),
    ]
