# Generated by Django 3.0 on 2024-01-09 18:46

from django.db import migrations
from django.core.serializers import serialize


def backup_address(apps, schema_editor):
    address = apps.get_model('oc_lettings_site', 'Address')
    data = serialize('json', address.objects.all())
    with open('address_backup.json', 'w') as f:
        f.write(data)

def backup_letting(apps, schema_editor):
    letting = apps.get_model('oc_lettings_site', 'Letting')
    data = serialize('json', letting.objects.all())
    with open('letting_backup.json', 'w') as f:
        f.write(data)

def backup_profile(apps, schema_editor):
    profile = apps.get_model('oc_lettings_site', 'Profile')
    data = serialize('json', profile.objects.all())
    with open('profile_backup.json', 'w') as f:
        f.write(data)


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backup_profile),
        migrations.RunPython(backup_address),
        migrations.RunPython(backup_letting),
    ]
